name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  # call-review-pipeline:
  #   uses: ./.github/workflows/review-pipeline.yaml
  
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform -chdir=infra/prerequisites init

      - name: Terraform Plan
        run: terraform -chdir=infra/prerequisites plan

      - name: Terraform Apply
        run: terraform -chdir=infra/prerequisites apply -auto-approve
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_env: ${{ secrets.ENV }}
          TF_VAR_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

      - id: terraform_ecr_repo_url_output
        name: Get ECR Repository URL
        run: echo "::set-output name=ecr_url::$(terraform -chdir=infra/prerequisites output -raw ecr_repo_url)"

      - id: terraform_lambda_execution_role_output
        name: Get Lambda Execution Role ARN
        run: echo "::set-output name=ecr_url::$(terraform -chdir=infra/prerequisites output -raw lambda_exec_role_arn)"
